export enum Action {
	SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE',
	SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT',
	SET_NEW_PAGE = 'SET_NEW_PAGE',
	SET_NEW_COMPONENT = 'SET_NEW_COMPONENT',
	DELETE_ACTIVE_PAGE = 'DELETE_ACTIVE_PAGE',
	DELETE_ACTIVE_COMPONENT = 'DELETE_ACTIVE_COMPONENT'
}
