export enum Action {
	SET_WEBSITE = 'SET_WEBSITE',
	ADD_PAGE = 'ADD_PAGE',
	ADD_COMPONENT = 'ADD_COMPONENT',
	ADD_STYLE = 'ADD_STYLE',
	UPDATE_WEBSITE = 'UPDATE_WEBSITE',
	UPDATE_PAGE = 'UPDATE_PAGE',
	UPDATE_COMPONENT = 'UPDATE_COMPONENT',
	UPDATE_STYLE = 'UPDATE_STYLE',
	DELETE_WEBSITE = 'DELETE_WEBSITE',
	DELETE_PAGE = 'DELETE_PAGE',
	DELETE_COMPONENT = 'DELETE_COMPONENT'
}
